# Slack Logger設定ファイル(特に秘密ではないデジタル民主主義2030の設定)

# スキップするチャンネル（IDまたは名前）
skip_channels:
  - C08JQERPAJ2 # 8_開発_いどばた_github
  - C08JQEUR79U # 8_開発_広聴ai_github
  - C08PRQVQWSE # 8_devinと人間たちの部屋

# 自動参加設定
auto_join: true

# 出力設定
output:
  default_dir: ./data
  timezone: Asia/Tokyo
